name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert

  size-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check package size
      run: |
        cd amazonq-sdd
        SIZE=$(du -sb install.js | cut -f1)
        echo "Package size: $SIZE bytes"
        if [ $SIZE -gt 100000 ]; then
          echo "⚠️ Warning: Package size exceeds 100KB"
          exit 1
        fi

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check code quality
      run: |
        cd amazonq-sdd
        echo "✅ Code quality check passed - simple NPM package structure"
        node install.js --help > /dev/null
        echo "✅ Package executes successfully"

  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Test package functionality
      run: |
        cd amazonq-sdd
        npm test
        echo "✅ Tests passed"